name = "forgithub_genignore"
compatibility_date = "2025-04-17"
dev.port = 3000
main = "./main.ts"
routes = [
  { pattern = "genignore.forgithub.com", custom_domain = true }
]
assets.directory = "./public"